### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by L-Cool-J** [eolinker/goku#13]
我按照[教程]( https://help.eolinker.com/#/tutorial/?groupID=c-252&productID=19)来, 为什么教程上面说好的[安装界面](http://服务器地址:9901),到我这就成了登录界面了, 怎么也登录不进去

**Comment by c5433137** [comment]
首次登陆 把config下的内容清空即可登陆

**Comment by eolinker** [comment]
GOKU更新了最新的版本，欢迎体验新的版本。
