### ISSUE TITLE
json格式转发好像有问题

### ISSUE THREAD

**Issue by zhangdong1015** [eolinker/goku#5]
Body为Raw数据是表示json格式的，但是在代码中this.isJSON = false,
// Set raw message body
// NOTICE: it is the users' responsability to set the correct Content-Type header
func (this *request) SetRawBody(body []byte) Request {
	this.isJSON = false
	this.body = body
	return this
}

**Comment by eolinker** [comment]
GOKU更新了最新的版本，欢迎体验新版本
