### ISSUE TITLE
Few questions regarding goku

### ISSUE THREAD

**Issue by rohan-97** [eolinker/goku#86]
Hello,

I was planning to introduce API gateway in my existing application.
I was going over different API gateways,
I have few queries

1. is this project actively maintained?
2. Are there plugins available for LDAP authentication and authorization?
3. If plugins are not available, can I create my custom plugins using golang? 

Thanks in advance!

**Comment by KaiJunYan** [comment]
I think  all answers of your issues is  NO !
the only way to resolve your issues is Money ! Buy It  and you will get attention 。

**Comment by eolinker** [comment]
Thanks for your attention.
The Goku project is undergoing large-scale reconstruction, and the current version has entered the process of gradual suspension of maintenance. The new open source gateway will be donated to the Linux foundation for maintenance in a more comprehensive, deeper and more open way. You can look forward to our new version later.
