### ISSUE TITLE
是诚心开源么

### ISSUE THREAD

**Issue by KaiJunYan** [eolinker/goku#87]
- 没有QQ群或者微信群，issue也不活跃，有问题都不知道哪里获得回答
 - README中很多链接已经不对了，也不进行维护的，比如部署教程、快速入门教程和源码编译教程
 - [API 微服务网关平台教程](https://help.eolinker.com/private_cloud/api_gateway/html/index.html)这个文档里面是企业版和开源版本混搭的，和最新开源的docker镜像也是对不上的，很混乱

**Comment by eolinker** [comment]
非常抱歉给您造成了困扰,我们已经将项目捐献给 TARS基金会, 我们目前正在紧锣密鼓进行全新版本的整理工作,争取尽快将全新设计的goku网关提供给用户.
由于人力的问题, 没有及时更新开源版本的文档导致的问题,我们深感抱歉, 我们已经在招聘新成员用于开源方面的维护
新版本将是颠覆性的, 敬请期待

**Comment by xhorizon** [comment]
别想了哦，他家以前的Api管理系统，新版闭源过后，旧版仓库直接都看不到了，只能从别人fork的上面还能找到，这种公司一看就不是诚心做开源的。

> 
> 
>     * 没有QQ群或者微信群，issue也不活跃，有问题都不知道哪里获得回答
> 
>     * README中很多链接已经不对了，也不进行维护的，比如部署教程、快速入门教程和源码编译教程
> 
>     * [API 微服务网关平台教程](https://help.eolinker.com/private_cloud/api_gateway/html/index.html)这个文档里面是企业版和开源版本混搭的，和最新开源的docker镜像也是对不上的，很混乱

**Comment by eolinker** [comment]
> 别想了哦，他家以前的Api管理系统，新版闭源过后，旧版仓库直接都看不到了，只能从别人fork的上面还能找到，这种公司一看就不是诚心做开源的。
> 
> > ```
> > * 没有QQ群或者微信群，issue也不活跃，有问题都不知道哪里获得回答
> > 
> > * README中很多链接已经不对了，也不进行维护的，比如部署教程、快速入门教程和源码编译教程
> > 
> > * [API 微服务网关平台教程](https://help.eolinker.com/private_cloud/api_gateway/html/index.html)这个文档里面是企业版和开源版本混搭的，和最新开源的docker镜像也是对不上的，很混乱
> > ```

Eolinker曾在2016年发布过开源的API管理工具，后面由于推出了免费的SaaS服务，由于人手原因，为了更好地打造SaaS产品，因此于2018年停止了开源产品的维护。

如果对API管理产品有需求，可以访问我们的SaaS产品进行了解呢。

---

另外，接下来会有全新的开源网关产品发布，如果有兴趣可以一起参与进来，目前正在筹划中。

**Comment by eolinker** [comment]
> 别想了哦，他家以前的Api管理系统，新版闭源过后，旧版仓库直接都看不到了，只能从别人fork的上面还能找到，这种公司一看就不是诚心做开源的。
> 
> > ```
> > * 没有QQ群或者微信群，issue也不活跃，有问题都不知道哪里获得回答
> > 
> > * README中很多链接已经不对了，也不进行维护的，比如部署教程、快速入门教程和源码编译教程
> > 
> > * [API 微服务网关平台教程](https://help.eolinker.com/private_cloud/api_gateway/html/index.html)这个文档里面是企业版和开源版本混搭的，和最新开源的docker镜像也是对不上的，很混乱
> > ```

看了您的账号，似乎并没有贡献过开源项目或代码，如果您对开源产品感兴趣，欢迎加入成为我们的Committer~
